
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100  
  
  # Velocity Controllers ---------------------------------------
  head_swivel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: head_swivel
    pid: {p: 100.0, i: 0.01, d: 10.0}
